name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure git user info
        run: |
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"

      - name: Pull remote changes (review before merge)  # Optional, comment out if not needed
        run: |
          git remote set-url origin https://github.com/appsaeed/laravel-saas-app
          git pull --rebase

      - name: Add files
        run: |
          git add .htaccess

      - name: Commit changes
        run: |
          git commit -m "Automated push from GitHub Actions"

      - name: Push to repo
        run: |
          git push origin main
