name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Push to target repo
        run: |
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"
          git add README.md
          git commit -m "Automated push from GitHub Actions (README.md)"
          git push https://github.com/appsaeed/laravel-saas-task HEAD:main
