name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Push to target repo
        run: |
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"
          git remote set-url origin https://github.com/appsaeed/laravel-saas-app
          git pull --all
          git add .htaccess
          git commit -m "Automated push from GitHub Actions"
          git push origin main

