name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Push to target repo
        run: |
          mkdir test
          cp README.md test/README.md
          cp .htaccess test/.htaccess
          cd test
          git init
          git remote add origin https://github.com/appsaeed/laravel-saas-app
          git pull --all
          git checkout main
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"
          git add .
          git commit -m "Automated push from GitHub Actions"
          git push origin main --force
