name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Push to target repo
        run: |
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"

          git clone https://github.com/appsaeed/laravel-saas-app

          cp README.md laravel-saas-app/README.md

          cd laravel-saas-app
          git add .
          git commit -m "Automated push from GitHub Actions"
          git push origin --force
