name: Push to Laravel SaaS App
on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure user info (not recommended for security)
        run: |
          git config --local user.email "appsaeed7@gmail.com"
          git config --local user.name "appsaeed"

      - name: Pull remote changes (review before merge)  # Optional, comment out if not needed
        run: |
          git pull

      - name: Add .htaccess (if needed)
        run: |
          git add .htaccess

      - name: Commit changes (optional)
        run: |
          git commit -m "Automated push from GitHub Actions"  # Only commit if needed

      - name: Push to target repo
        run: |
          git remote set-url origin https://github.com/appsaeed/laravel-saas-app  # Sets the remote URL
          git push origin main
