name: Clone and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone private repo
        run: git clone https://appsaeed:${{ secrets.GPA_TOKEN }}@github.com/appsaeed/laravel-saas-task.git private-repo
      
      - name: Navigate to cloned repo
        run: cd private-repo
      - run: rm -rf private-repo/.git
      - run: cp -R private-repo/. .

      # Commit and push to current repo
      - name: Commit and push to current repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md && git commit -m "Automated commit (README.md)"
          git push origin main --force
