name: Clone and Push

on:
  schedule:
    # every 24 hours
    - cron: "0 0 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # On changes
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone repo
        run: git clone https://appsaeed:${{ secrets.GPA_TOKEN }}@github.com/appsaeed/${{ vars.CLONE_REPO }}.git cloned-repo

      - run: rm -rf cloned-repo/.git

      - run: cp -R cloned-repo/. .

      # Commit and push to current repo
      - name: Commit and push to current repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md .htaccess artisan
          git commit -m "Automated commit (README.md)"
          git push origin main --force
