name: Clone and Push to Parent

on: [push]  # Trigger on push events

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2  # Checkout the parent repo (optional)
        with:
          repository: ${{ github.repository }}  # Current repo (parent)

      - name: Clone Private Repo
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git clone https://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@github.com/appsaeed/laravel-saas-task.git private-repo

      - name: Push to Parent Repo (optional)
        run: |
          cd private-repo
          # Add any modifications here (optional)
          git add .
          git commit -m "Pushed from private repo"
          git push origin main  # Adjust branch name if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the secret here
